
#include <Render/OpenGL/OpenGL.h>

// Color mapping
int COLOR_RGB = GL_RGB;
int COLOR_RGBA = GL_RGBA;
int COLOR_RGB16F = GL_RGB16F;
int COLOR_RED = GL_RED;
int COLOR_RED16F = GL_R16F;
int COLOR_RED32F = GL_R32F;
int COLOR_DEPTH_COMPONENT32 = GL_DEPTH_COMPONENT32;
int COLOR_DEPTH_COMPONENT = GL_DEPTH_COMPONENT;
