
#include <Render/OpenGL/OpenGL.h>

// Color mapping
int COLOR_RGB = GL_RGB;
int COLOR_RGBA = GL_RGBA;
int COLOR_RGB16F = GL_RGB16F;
int COLOR_RED = GL_RED;
int COLOR_RED16F = GL_R16F;
int COLOR_RED32F = GL_R32F;
int COLOR_DEPTH_COMPONENT32F = GL_DEPTH_COMPONENT32F;
int COLOR_DEPTH_COMPONENT = GL_DEPTH_COMPONENT;

int TEST_EQUAL = GL_EQUAL;
int TEST_LEQUAL = GL_LEQUAL;
int TEST_GEQUAL = GL_GEQUAL;
int TEST_LESS = GL_LESS;
int TEST_GREATER = GL_GREATER;

int FILTER_NEAREST = GL_NEAREST;
int FILTER_LINEAR = GL_LINEAR;

int COLOR_BUFFER_BIT = GL_COLOR_BUFFER_BIT;
int DEPTH_BUFFER_BIT = GL_DEPTH_BUFFER_BIT;
int STENCIL_BUFFER_BIT = GL_STENCIL_BUFFER_BIT;

int DRAW_TRIANGLES = GL_TRIANGLES;
int DRAW_TRIANGLE_STRIP = GL_TRIANGLE_STRIP;

int DRAW_BUFFER_NONE = GL_NONE;
int DRAW_BUFFER_FRONT = GL_FRONT;
int DRAW_BUFFER_BACK = GL_BACK;

int BLEND_ZERO = GL_ZERO;
int BLEND_ONE = GL_ONE;
int BLEND_SRC_COLOR = GL_SRC_COLOR;
int BLEND_ONE_MINUS_SRC_COLOR = GL_ONE_MINUS_SRC_COLOR;
int BLEND_SRC_ALPHA = GL_SRC_ALPHA;
int BLEND_ONE_MINUS_SRC_ALPHA = GL_ONE_MINUS_SRC_ALPHA;
int BLEND_DST_ALPHA = GL_DST_ALPHA;
int BLEND_ONE_MINUS_DST_ALPHA = GL_ONE_MINUS_DST_ALPHA;
